# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and package-lock for dependencies
COPY package*.json ./

# Install dependencies without running any prepare scripts
RUN npm ci --ignore-scripts

# Copy the rest of the application code
COPY . .

# Use a non-root user (optional)
# RUN addgroup -S appgroup && adduser -S appuser -G appgroup
# USER appuser

# Set the entrypoint for stdio server
ENTRYPOINT ["node", "src/index.js"]
